apiVersion: v2
name: kdiag
description: Explainable Kubernetes diagnostics platform
type: application
version: 0.4.0
appVersion: "0.4.0"
home: https://github.com/zhengcongyu/kdiag
sources:
  - https://github.com/zhengcongyu/kdiag
