{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kdiag.fullname" . }}
  labels:
    {{- include "kdiag.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {app.kubernetes.io/name: kdiag}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - {protocol: TCP, port: 8080}
{{- end }}

